[info]
name = "myproject"
autostart = true # Start on system boot
maxmemory = 512 # If not specified infinite

[commands]
prerun = "npm install"
startup = "node index.js"
after = "echo 'Process finished with exit code $?'"
