[info]
name = "test"
autostart = true # Start on system boot
maxmemory = 512 # If value is 0, no memory limit will be set

[commands]
prerun = "npm install"
startup = "node index.js"
after = "echo 'Process finished with exit code $?'"
